parameters:
    my_user_provider.class: ZZ\Bundles\UserBundle\Security\Core\User\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: [@fos_user.user_manager,{google: google_id}]

    zz_user.registration.form.type:
        class: ZZ\Bundles\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: zz_user_registration }