zz_bundles_app_homepage:
    pattern:  /
    defaults: { _controller: ZZBundlesAppBundle:App:index }

zz_bundles_app_cigarette:
    resource: "@ZZBundlesAppBundle/Resources/config/routing/cigarette.yml"
    prefix: /cigarette

zz_bundles_app_cigarette:
    resource: "@ZZBundlesAppBundle/Resources/config/routing/usersmoke.yml"
    prefix: /home

zz_app_usersmoke_show:
    pattern:  /{slug}
    defaults: { _controller: "ZZBundlesAppBundle:UserSmoke:show" }