parameters:
#    zz_bundles_app.example.class: ZZ\Bundles\AppBundle\Example

services:
#    zz_bundles_app.example:
#        class: %zz_bundles_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
